# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='application',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7528\u9014'),
        ),
        migrations.AddField(
            model_name='host',
            name='principal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8d1f\u8d23\u4eba'),
        ),
    ]
