# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20180315_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='usage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7528\u9014'),
        ),
        migrations.AlterField(
            model_name='host',
            name='application',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8f6f\u4ef6'),
        ),
    ]
