# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20180319_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='add_time',
            field=models.DateTimeField(blank=True, max_length=200, null=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='host',
            name='jira',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u7533\u8bf7jira'),
        ),
    ]
